services:
  - type: web
    name: youtube-downloader-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PRODUCTION
        value: "true"