services:
  - type: web
    name: youtube-downloader-api
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    plan: free
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11"