services:
  - type: web
    name: youtube-downloader-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11"